### PR TITLE
Style mail modules

### LINKED ISSUE #251: Style Mail Templates
The mail templates are pretty barebone...they need styling

### LINKED ISSUE #278: Remove required password for account delete

### PR DESCRIPTION
**Pull request by coffemakingtoaster**
# Changes
- add the best css you have ever laid eyes upon
- update swagger
- remove password requirement for account deletion (according to request from @Zoe-Bot )

Screenshots below. Note: In the screenshot for the account deleted the wrong font is used in the header. This has been fixed.

Closes #251 
Closes #278

### CODE REVIEW

**Comment by coffemakingtoaster** [comment]
Screenshot 2023-07-29 at 17 13 35

Screenshot 2023-07-29 at 17 21 29

Screenshot 2023-07-29 at 17 22 24

Screenshot 2023-07-29 at 17 24 41

**Review by Branchverse — COMMENTED** [review]
Reviewed everything besides .ejs files
LGTM

**Comment by Branchverse** [comment]
image

Black hmmm, not so sure bout that

image

Different Font than rest or am I hallucinating?

**Comment by coffemakingtoaster** [comment]
> image
> 
> Black hmmm, not so sure bout that
> 
> image
> 
> Different Font than rest or am I hallucinating?

You are not hallucinating, just not reading the PR description

**Review by Branchverse — APPROVED** [review]
LGTM

**Pull request merged**
